### ISSUE TITLE
🙋‍♂️ 一些建议或者说想对大佬说的话

### ISSUE THREAD

**Issue by vinceying** [unix/unix.bio#13]
首先，对大佬的努力表示感谢，unix.bio 博客做的非常简洁和好看，而且扩展强大，可以使用 `@zeit-ui/react`。
另外，由于渲染的问题，如果生成静态页面会有一些路径的问题，不知道除了 `npm run export` ，因为 vercel 的速度，还有没有什么部署在服务器上的方法。另外大佬有没有考虑过基于 zeit-ui 的风格开发一款 hexo 主题或者其它便于部署在服务器或者静态托管配图的主题，感觉会非常不错。

**Comment by unix** [comment]
感谢关注。对于你说的路径问题：
  1. 运行 `npm run export` 之后输出的文件在 `./out` 文件夹。
  2. 将 `./out` 文件夹作为根目录 copy 至你的静态服务器即可。
  3. 如果你希望使用 CDN 处理静态文件，请将环境变量设置为 CDN 前缀即可：

```bash
# set CDN prefix
export CDN_PREFIX=https://unix.bio
npm run export
```

以上功能支持需要最新版本的代码，请先运行 `npx unix-bio migrate` 自动迁移以更新博客源码。

对所有人：
我暂时没有在其他博客平台开发主题的想法，现在太忙了。(未来可能会，我不能承诺一个时间)
如果你想赞助我或是捐赠项目到 `zeit-ui`，请邮件联系我或是直接打开一个新的 Issue，我会很乐意告诉你该怎么做。

**Comment by vinceying** [comment]
> 感谢关注。对于你说的路径问题：
> 
> 1. 运行 `npm run export` 之后输出的文件在 `./out` 文件夹。
> 2. 将 `./out` 文件夹作为根目录 copy 至你的静态服务器即可。
> 3. 如果你希望使用 CDN 处理静态文件，请将环境变量设置为 CDN 前缀即可：
> 
> ```shell
> # set CDN prefix
> export CDN_PREFIX=https://unix.bio
> npm run export
> ```
> 
> 以上功能支持需要最新版本的代码，请先运行 `npx unix-bio migrate` 自动迁移以更新博客源码。
> 
> 对所有人：
> 我暂时没有在其他博客平台开发主题的想法，现在太忙了。(未来可能会，我不能承诺一个时间)
> 如果你想赞助我或是捐赠项目到 `zeit-ui`，请邮件联系我或是直接打开一个新的 Issue，我会很乐意告诉你该怎么做。

感谢大佬的回复，你的回复特别是 CDN 部分对我帮助很大。另外还有一个问题请教，就是将博客部署在服务器上，使用导航栏切换某个页面可以切换（比如切换关于页面），但是刷新一下或者使用地址访问会出现404。

![U3Kh8O.png](https://s1.ax1x.com/2020/07/12/U3Kh8O.png)
![U3KfPK.png](https://s1.ax1x.com/2020/07/12/U3KfPK.png)

服务器环境：Nginx 1.18.0
地址是：https://blog.vince.pub/

**Comment by unix** [comment]
这是你自己 Nginx 配置问题，搜索 SPA + Nginx 配置。
