### ISSUE TITLE
在禁用 Views 后，文章页仍然出现相关请求

### ISSUE THREAD

**Issue by FreshP0325** [unix/unix.bio#30]
在 `/blog.config.js` `lib/utils.ts` 均选择禁用 enableViews 后，访问文章页仍然会出现一个 fetch 请求：

![image](https://user-images.githubusercontent.com/54257356/152983468-06ad269f-d269-45e2-bbbb-a25f2aced098.png)

请问该如何彻底禁用该功能呢？

**Comment by unix** [comment]
是的，你可以在 [这里](https://github.com/unix/unix.bio/blob/5550890ec293e0d6414473646c697c7ff333b838/lib/components/title.tsx#L15) 移除功能。

**Comment by FreshP0325** [comment]
删除第 15 行后，会报错

```
Type error: 'useViews' is declared but its value is never read.
```

如果继续删除第 6 行，则有下面的错误

```
Type error: 'asPath' is declared but its value is never read.
```

**Comment by unix** [comment]
声明但未使用，只要把这几个变量注释一下即可，L14 L4。
