### ISSUE TITLE
希望提供详细的配置文件模板

### ISSUE THREAD

**Issue by CooperLi** [unix/unix.bio#6]
初次使用博客，感觉很不错！

在易用性方面，能做到开箱即用，大赞！

自定义配置方面，因为没有接触过nodejs， 所以不太清楚怎么去自定义博客的配置
虽然在`blog.config.js`里面已经包含了一些基础配置，但是没有找到自己想要的，比如设置字体大小等基础功能和高级功能的配置方式，希望能够提供一个比较**全面** 的配置文件供玩家参考。

再次感谢你的作品！

**Comment by unix** [comment]
好提议。
我会增加一个 `Wiki` 页面用来解释每个配置项的作用，以及必选项。随后我会增加更多的自定义项。

这个 Feature 与文档大约需要 1 - 2 工作日。当完成时我会在此提醒你。

**Comment by unix** [comment]
@CooperLi 

我在这里增加了博客的 [所有配置项文档](https://github.com/unix/unix.bio/wiki/%E5%8D%9A%E5%AE%A2%E6%89%80%E6%9C%89%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9)。如果你有其他需要的配置请告诉我，我视情况加入总体配置中，或是告诉你应该更改哪里。

配置项没有囊括所有的主题可用项有以下几个原因：

  - 色彩是双主题的，每配置一个色彩需要同时考虑 **明 / 暗** 两种风格
  - 部分设置复用性较低，但还是可能涉及 **移动端 / 桌面端** 两种配置

有任何问题请留言，重新打开问题。
