### ISSUE TITLE
If the summary is too long, it will not adapt itself on the small screen device.

### ISSUE THREAD

**Issue by ifvv** [unix/unix.bio#7]
![image](https://user-images.githubusercontent.com/57923430/80125369-29d30180-85c4-11ea-8fde-1b15bbc6b0a8.png)

**Comment by unix** [comment]
fixed in this [commit](https://github.com/unix/unix.bio/commit/400cc992e0b0ae491bedf41f72d9a9b5ce78593d).
run `npx unix-bio migrate` to upgrade source codes.
